#!/bin/bash

awk '
BEGIN {
	upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	lower = "abcdefghijklmnopqrstuvwxyz"
}

{
	while ( match($0, /[A-Z]+/) )
		for (x = RSTART; x < RSTART+RLENGTH; ++x) {
			CAP = substr($0, x, 1)
			CHAR = index(upper, CAP)
			gsub(CAP, substr(lower, CHAR, 1))
		}
	print $0
}' $*
